import DashboardLayout from '@/Layouts/DashboardLayout';
import { Head, Link, router } from '@inertiajs/react';

type Entry = { kind: string; id: number; reference: string; reason: string; companyName: string | null; orderNumber: string | null; trackingNumber: string | null; status: string; responsibleName: string | null; blocker: string | null; canResolve: boolean };
export default function Exceptions({ exceptions, filters, sourceGaps }: { exceptions: { data: Entry[]; total: number; links: { url: string | null; label: string; active: boolean }[] }; filters: { kind?: string; status?: string }; sourceGaps: { total: number; data: { orderNumber: string; trackingNumber: string; reason: string }[] } }) {
    const filter = (key: string, value: string) => router.get('/exceptions', { ...filters, [key]: value }, { preserveState: true });
    return <DashboardLayout title="Delivery exceptions" subtitle="Review actual problems and recovery evidence"><Head title="Delivery exceptions" /><div className="space-y-5">
        <p className="text-sm text-slate-600">Follow up on restrictions, failed attempts, manifest discrepancies and counter holding. Physical handovers stay with the responsible rider, hub handler or seller.</p>
        <div className="flex flex-wrap gap-3"><label className="text-sm text-slate-700">Case type<select className="ml-2 rounded-lg border-slate-300 text-sm" value={filters.kind ?? ''} onChange={e => filter('kind', e.target.value)}><option value="">All types</option><option value="restriction">Restrictions</option><option value="attempt">Failed attempts</option><option value="manifest">Manifest discrepancies</option><option value="pickup">Counter holding</option></select></label>
            <label className="text-sm text-slate-700">Review status<select className="ml-2 rounded-lg border-slate-300 text-sm" value={filters.status ?? 'open'} onChange={e => filter('status', e.target.value)}><option value="open">Open</option><option value="resolved">Resolved</option><option value="all">All</option></select></label><span className="self-center text-sm text-slate-500">{exceptions.total} cases</span></div>
        {!exceptions.data.length && <p className="rounded-lg border border-slate-300 bg-white p-6 text-sm text-slate-600">No recorded cases match this view.</p>}
        {sourceGaps.total > 0 && <section className="rounded-lg border border-amber-300 bg-amber-50 p-4"><h2 className="font-semibold text-amber-900">Missing source records ({sourceGaps.total})</h2><ul className="mt-2 space-y-3">{sourceGaps.data.map(parcel => <li key={parcel.trackingNumber} className="text-sm text-amber-900"><p className="font-semibold">{parcel.orderNumber} · {parcel.trackingNumber}</p><p>{parcel.reason.replaceAll('_', ' ')}</p></li>)}</ul>{sourceGaps.total > sourceGaps.data.length && <p className="mt-2 text-sm text-amber-900">Showing the first {sourceGaps.data.length} affected parcels. The remaining records also require source recovery.</p>}</section>}
        <div className="grid gap-3">{exceptions.data.map(item => <Link key={`${item.kind}-${item.id}`} href={`/exceptions/${item.kind}/${item.id}`} className="rounded-lg border border-slate-300 bg-white p-4 shadow-sm hover:border-[#E00D42]">
            <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold text-slate-900">{item.orderNumber ?? item.reference}</h2><span className="rounded-lg bg-slate-100 px-2 py-1 text-xs capitalize">{item.status}</span></div>
            <p className="mt-1 text-sm text-slate-600">{item.trackingNumber ?? item.reference} · {item.companyName ?? 'Platform review'}</p><p className="mt-2 text-sm">{item.reason.replaceAll('_', ' ')}</p><p className="mt-2 text-xs text-slate-600">Responsible: {item.responsibleName ?? 'Awaiting assignment'}</p>
            {item.status === 'open' && <p className={`mt-2 text-sm ${item.canResolve ? 'text-emerald-700' : 'text-amber-800'}`}>{item.canResolve ? 'Source evidence is available for review.' : item.blocker}</p>}
        </Link>)}</div>
        <nav aria-label="Exception pages" className="flex flex-wrap gap-2">{exceptions.links.map((link, index) => link.url ? <Link key={index} href={link.url} className={`rounded-lg border border-slate-300 px-3 py-2 text-sm ${link.active ? 'bg-[#E00D42] text-white' : 'bg-white'}`} dangerouslySetInnerHTML={{ __html: link.label }} /> : <span key={index} className="px-3 py-2 text-sm text-slate-400" dangerouslySetInnerHTML={{ __html: link.label }} />)}</nav>
    </div></DashboardLayout>;
}
