import React from 'react';
import { Head, Link } from '@inertiajs/react';
import DashboardLayout from '@/Layouts/DashboardLayout';
import AdminFinanceAvailability from '@/Components/AdminFinanceAvailability';
import { recordLabel } from '@/Components/GovernanceRecord';
import type { AdminOverviewProps } from '@/types/admin';
import { formatPhpDecimal } from '@/utils/money';

export default function AdminDashboard({ stats, queues, finance, orderStates, workReferences, recentOrders, recentUsers }: AdminOverviewProps) {
    return <DashboardLayout title="Platform overview" subtitle="Recorded review queues, account states and parcel activity" actions={<Link href={route('admin.users')} className="rounded-lg bg-[#E00D42] px-4 py-2 text-sm font-semibold text-white">Review accounts</Link>}>
        <Head title="Platform overview — Bagoo Admin" />
        <div className="space-y-6">
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
                <section className="rounded-xl border border-slate-300 bg-white p-5"><p className="text-sm text-slate-500">Recorded paid order gross</p><p className="mt-2 text-2xl font-semibold text-slate-900">{formatPhpDecimal(stats.paidOrderGross)}</p><p className="mt-2 text-xs leading-5 text-slate-500">Sum of order totals with payment status paid · {stats.paidOrderCount} orders. Includes recorded shipping and discounts; this is not commission or reconciled cash.</p></section>
                {[
                    ['Order records', stats.totalOrders, 'All recorded orders, including cancelled and returned orders'],
                    ['Open parcels', stats.openParcels, 'Known open pickup, hub, delivery and recovery states'],
                    ['Delivered orders awaiting buyer confirmation', stats.deliveredAwaitingBuyer, 'Only the buyer can confirm receipt and complete an order'],
                ].map(([label, count, description]) => <section key={String(label)} className="rounded-xl border border-slate-300 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{count}</p><p className="mt-2 text-xs leading-5 text-slate-500">{description}</p></section>)}
            </div>
            <section className="rounded-xl border border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Review queues</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{queues.map((queue) => <Link key={queue.label} href={queue.url} className="rounded-lg border border-slate-300 p-4 hover:border-[#E00D42]"><p className="text-sm text-slate-600">{queue.label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{queue.count}</p><p className="mt-2 text-xs font-semibold text-[#E00D42]">Open records</p></Link>)}</div></section>
            <section className="rounded-xl border border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Registered roles · {stats.totalUsers} current accounts</h2><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-5">{Object.entries(stats.usersByRole).map(([role, count]) => <div key={role} className="rounded-lg border border-slate-300 bg-slate-50 p-4"><p className="text-sm text-slate-600">{role === 'logistics' ? 'Logistics / hub accounts' : recordLabel(role)}</p><p className="mt-2 text-2xl font-semibold">{count}</p></div>)}</div>{stats.unknownRoles > 0 && <p className="mt-4 text-sm text-amber-700">{stats.unknownRoles} accounts have an unrecognized recorded role and need controlled review.</p>}<p className="mt-4 text-xs text-slate-500">Roles include active, restricted and pending accounts. Pickup and delivery are courier phases.</p></section>
            <section className="rounded-xl border border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Recorded network and listings</h2><div className="mt-4 grid gap-4 text-sm sm:grid-cols-2 xl:grid-cols-4"><p>{stats.companies} companies · {stats.eligibleCompanies} eligible</p><p>{stats.hubs} facilities · {stats.eligibleHubs} eligible</p><p>{stats.onDutyEligibleRiders} on-duty riders with eligible network placement</p><p>{stats.totalProducts} product records</p></div><p className="mt-4 text-xs text-slate-500">Duty is a stored preference. Live presence and GPS are unavailable; an eligible network placement does not establish an idle rider.</p></section>
            <div className="grid gap-6 lg:grid-cols-2">
                <section className="rounded-xl border border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Recorded order states</h2>{orderStates.length ? <dl className="mt-5 space-y-3">{orderStates.map((state) => <div key={state.status} className="flex justify-between gap-4 text-sm"><dt className="text-slate-600">{state.label} <span className="text-xs text-slate-400">({state.status})</span></dt><dd className="font-semibold">{state.count}</dd></div>)}</dl> : <p className="mt-5 text-sm text-slate-500">No order records yet.</p>}<p className="mt-4 text-xs text-slate-500">Counts use each order’s exact stored state. Legacy states are retained separately.</p></section>
                <section className="rounded-xl border border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Open work linked to recorded restrictions</h2><p className="mt-2 text-xs leading-5 text-slate-500">Recent references link current open orders to the original restriction. They do not establish a current custodian or an unresolved exception.</p>{workReferences.length ? <div className="mt-5 space-y-4">{workReferences.map((work) => <div key={work.order_id} className="border-b border-slate-200 pb-3 text-sm last:border-0"><Link href={work.order_url} className="font-semibold text-[#E00D42] hover:underline">{work.number}</Link><p className="mt-1 text-slate-600">{recordLabel(work.status)}</p><Link href={work.decision_url} className="mt-1 inline-block text-xs font-semibold text-[#E00D42] hover:underline">View recorded restriction</Link></div>)}</div> : <p className="mt-5 text-sm text-slate-500">No recorded restriction references match current open orders.</p>}<button disabled className="mt-5 rounded-lg border border-slate-300 bg-slate-100 px-3 py-2 text-sm text-slate-500">Exception actions unavailable</button><p className="mt-2 text-xs text-slate-500">Recovery actions require the later exception oversight module.</p></section>
            </div>
            <AdminFinanceAvailability finance={finance} />
            <div className="grid gap-6 lg:grid-cols-2">
                <section className="rounded-xl border border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Recent order records</h2>{recentOrders.length ? <div className="mt-5 space-y-4">{recentOrders.map((order) => <div key={order.id} className="flex items-start justify-between gap-4 border-b border-slate-200 pb-4 text-sm last:border-0"><div><Link href={order.url} className="font-semibold text-[#E00D42] hover:underline">{order.order_number}</Link><p className="mt-1 text-slate-600">Buyer: {order.buyer_name ?? 'Unavailable'}</p><p className="text-xs text-slate-500">Pickup rider: {order.pickup_rider_name ?? 'Unassigned'} · Delivery rider: {order.delivery_rider_name ?? 'Unassigned'}</p><p className="mt-1 text-xs text-slate-500">{recordLabel(order.status)} · Payment: {recordLabel(order.payment_status)}</p></div><p className="whitespace-nowrap font-semibold">{formatPhpDecimal(order.total_amount)}</p></div>)}</div> : <p className="mt-5 text-sm text-slate-500">No orders have been recorded.</p>}</section>
                <section className="rounded-xl border border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Recent account registrations</h2>{recentUsers.length ? <div className="mt-5 space-y-4">{recentUsers.map((user) => <div key={user.id} className="border-b border-slate-200 pb-4 text-sm last:border-0"><Link href={user.url} className="font-semibold text-[#E00D42] hover:underline">{user.name}</Link><p className="break-words text-xs text-slate-500">{user.email}</p><p className="mt-1 text-xs text-slate-600">{recordLabel(user.role)} · Activity: {recordLabel(user.status)} · Approval: {user.role === 'admin' ? 'Controlled admin access' : (user.kyc_status ? recordLabel(user.kyc_status) : 'Unavailable')}</p></div>)}</div> : <p className="mt-5 text-sm text-slate-500">No current account records.</p>}</section>
            </div>
        </div>
    </DashboardLayout>;
}
