import React, { useState } from 'react';
import { Head, router, Link, usePage } from '@inertiajs/react';
import DashboardLayout from '@/Layouts/DashboardLayout';
import AdminFinanceAvailability from '@/Components/AdminFinanceAvailability';
import { recordLabel } from '@/Components/GovernanceRecord';
import type { AdminLogisticsProps } from '@/types/admin';
import type { PageProps } from '@/types';

export default function AdminLogistics({ deliveries, couriers, filters, stats, statusOptions, finance }: AdminLogisticsProps) {
    const [search, setSearch] = useState(filters.search);
    const [status, setStatus] = useState(filters.status);
    const { errors } = usePage<PageProps>().props;
    const control = 'rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus:border-[#E00D42] focus:ring-[#E00D42]';
    return <DashboardLayout title="Logistics oversight" subtitle="Platform-wide recorded parcels, rider placement and duty">
        <Head title="Logistics oversight — Bagoo Admin" />
        <div className="space-y-6">
            <div className="rounded-lg border border-slate-300 bg-slate-50 p-4 text-sm text-slate-700">This view is read only. Assigned riders and eligible hub handlers record parcel custody. Platform recovery actions are unavailable until exception oversight is implemented.</div>
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
                ['Parcel records', stats.total, 'All recorded parcels'],
                ['Open parcels', stats.open, 'Known open pickup, hub, delivery and recovery states'],
                ['Awaiting pickup assignment', stats.awaitingPickupAssignment, 'Unassigned state with no recorded rider'],
                ['Delivered or collected status', stats.handoverStatus, 'Delivered, customer collected or completed states; cash remains separate'],
            ].map(([label, count, note]) => <section key={String(label)} className="rounded-xl border border-slate-300 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{count}</p><p className="mt-2 text-xs leading-5 text-slate-500">{note}</p></section>)}</div>
            <section className="rounded-xl border border-slate-300 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold text-slate-900">Rider account roster</h2><Link href={route('admin.users', { role: 'courier' })} className="text-sm font-semibold text-[#E00D42] hover:underline">All rider accounts</Link></div><p className="mt-2 text-sm text-slate-600">Showing {couriers.length} of {stats.courierAccounts} accounts · {stats.onDutyEligibleRiders} on-duty riders have eligible network placement. Live presence is unavailable.</p>
                <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{couriers.map((rider) => <div key={rider.id} className="rounded-lg border border-slate-300 p-4"><h3 className="font-semibold text-slate-900">{rider.name} · #{rider.id}</h3><p className="mt-2 text-sm text-slate-700">Duty preference: {rider.on_duty === null ? 'Not recorded' : rider.on_duty ? 'On duty' : 'Off duty'}</p><p className="mt-1 text-xs text-slate-500">Activity: {recordLabel(rider.status)} · Approval: {rider.kyc_status ? recordLabel(rider.kyc_status) : 'Unavailable'}</p><p className="mt-1 text-xs text-slate-500">Company: {rider.company_id ? '#' + rider.company_id : 'Not assigned'} · Hub: {rider.hub_id ? '#' + rider.hub_id : 'Not assigned'}</p><p className="mt-1 text-xs text-slate-500">Network eligibility: {rider.network_eligible ? 'Eligible' : 'Not eligible'} · {rider.linked_open_parcels} linked open parcels</p></div>)}</div>
                {!couriers.length && <p className="mt-5 text-sm text-slate-500">No courier accounts are recorded.</p>}<p className="mt-4 text-xs text-slate-500">Linked parcels use recorded pickup or delivery rider references. Network eligibility and duty do not prove that a rider is idle or holds a parcel.</p>
            </section>
            <section className="rounded-xl border border-slate-300 bg-white p-6"><h2 className="font-semibold text-slate-900">Parcel registry</h2><p className="mt-2 text-sm text-slate-600">{stats.exceptions} parcels are in failed delivery or return-to-sender states. Counts cover the platform; table filters apply only to the registry below.</p>
                <form onSubmit={(event) => { event.preventDefault(); router.get(route('admin.logistics'), { search, status }, { preserveState: true }); }} className="mt-5 flex flex-wrap gap-3"><label className="grow text-sm text-slate-600">Search recorded parcels<input value={search} maxLength={100} onChange={(event) => setSearch(event.target.value)} placeholder="Tracking, order, seller or recipient" className={control + ' mt-1 block w-full'} /></label><label className="text-sm text-slate-600">Exact recorded state<select value={status} onChange={(event) => setStatus(event.target.value)} className={control + ' mt-1 block w-full'}><option value="all">All states</option>{statusOptions.map((option) => <option key={option.value} value={option.value}>{option.label} ({option.count})</option>)}</select></label><button className="self-end rounded-lg bg-[#E00D42] px-4 py-2 text-sm font-semibold text-white">Apply filters</button><button type="button" onClick={() => { setSearch(''); setStatus('all'); router.get(route('admin.logistics')); }} className="self-end rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Clear</button></form>
                {Object.keys(errors).length > 0 && <div role="alert" className="mt-3 text-sm text-rose-700">{Object.entries(errors).map(([field, message]) => <p key={field}>{message}</p>)}</div>}
                <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-300 text-xs text-slate-500"><tr>{['Tracking / order', 'Seller / recipient', 'Pickup rider', 'Delivery rider', 'Current recorded hub', 'Parcel state'].map((label) => <th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{deliveries.data.map((parcel) => <tr key={parcel.id}><td className="px-3 py-4"><p className="font-semibold">{parcel.tracking_number}</p>{parcel.order_url && <Link href={parcel.order_url} className="mt-1 block text-xs font-semibold text-[#E00D42] hover:underline">{parcel.order?.order_number ?? 'View order'}</Link>}</td><td className="px-3 py-4"><p>{parcel.pickup_store_name ?? 'Seller not recorded'}</p><p className="mt-1 text-xs text-slate-500">To: {parcel.delivery_recipient_name ?? 'Recipient not recorded'}</p><p className="max-w-xs text-xs text-slate-500">{parcel.delivery_address ?? 'Address not recorded'}</p></td><td className="px-3 py-4">{parcel.courier?.name ?? 'Unassigned'}</td><td className="px-3 py-4">{parcel.assigned_rider?.name ?? 'Unassigned'}</td><td className="px-3 py-4">{parcel.current_hub?.name ?? 'No current hub recorded'}</td><td className="px-3 py-4">{recordLabel(parcel.status)}</td></tr>)}</tbody></table></div>
                {!deliveries.data.length && <p className="py-8 text-center text-sm text-slate-500">No parcels match these filters.</p>}<div className="mt-5 flex justify-between gap-4 border-t border-slate-300 pt-4 text-sm"><p className="text-slate-600">{deliveries.total} matching parcels · Page {deliveries.current_page} of {deliveries.last_page}</p><div className="flex gap-3">{deliveries.prev_page_url && <Link href={deliveries.prev_page_url} className="rounded-lg border border-slate-300 px-3 py-2">Previous</Link>}{deliveries.next_page_url && <Link href={deliveries.next_page_url} className="rounded-lg border border-slate-300 px-3 py-2">Next</Link>}</div></div>
            </section>
            <AdminFinanceAvailability finance={finance} />
        </div>
    </DashboardLayout>;
}
